name: project_management

services:
  
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    env_file:
      - ./db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./pgadmin/.env
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: spring-backend
    env_file:
      - ./backend/.env
    
    
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: angular-frontend
    networks:
      - internal
    restart: unless-stopped
    

  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - public
      - internal
    depends_on:
      - frontend
      - backend
        
    restart: unless-stopped

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  postgres_data: