

-- Kreiraj projekti tabelu
CREATE TABLE projekti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR(255) NOT NULL,
    opis_projekta TEXT,
    rok_realizacije DATE NOT NULL
);

-- Kreiraj zadaci tabelu
CREATE TABLE zadaci (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projekta INTEGER NOT NULL,
    opis_zadatka TEXT NOT NULL,
    status_zadatka INTEGER NOT NULL DEFAULT 0,
    prioritet_zadatka INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_zadaci_projekti
        FOREIGN KEY (id_projekta)
        REFERENCES projekti(id)
        ON DELETE CASCADE
);

-- Ubaci test podatke
INSERT INTO projekti (id, naziv, opis_projekta, rok_realizacije) VALUES
(1, 'Redizajn aplikacije', 'Kompletna promena izgleda aplikacije', '2026-11-08'),
(2, 'Izrada Web sajta', 'Izrada sajta za Web prodavnicu', '2026-10-05'),
(3, 'REST aplikacija za upravljanje proizvodima', 'Izrada backenda sa CRUD operacijama', '2026-05-02');

INSERT INTO zadaci (id, id_projekta, opis_zadatka, status_zadatka, prioritet_zadatka) VALUES
(1, 2, 'Izrada backenda aplikacije', 1, 1),
(2, 1, 'Izrada dizajna', 2, 3),
(3, 3, 'Izrada CRUD operacija', 0, 0),
(4, 2, 'Autorizacija i autentifikacija JWT', 0, 0),
(5, 1, 'Izrada Angular komponenti', 0, 0);

-- Podesi sekvence nakon ručnog unosa ID vrednosti
SELECT setval(
    pg_get_serial_sequence('projekti', 'id'),
    (SELECT MAX(id) FROM projekti)
);

SELECT setval(
    pg_get_serial_sequence('zadaci', 'id'),
    (SELECT MAX(id) FROM zadaci)
);
